### ISSUE TITLE
macOS - no Swagger on  Tutorial: Create a web API 

### ISSUE THREAD

**Issue by downshiftdata** [dotnet/AspNetCore.Docs#21647]
Since this is a "Hello World" kind of situation, more help when things go wrong would be appreciated. I followed the instructions and the /Swagger URL wouldn't load. I'm sure I'm missing some prerequisite, but don't know what yet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
[Associated WorkItem - 97033](https://dev.azure.com/msft-skilling/Content/_workitems/edit/97033)

**Comment by Rick-Anderson** [comment]
Most likely you don't have .NET 5 installed.

**Comment by philiptkd** [comment]
I have .NET 5 installed and am having the same problem

**Comment by Rick-Anderson** [comment]
> I have .NET 5 installed and was having the same problem.
> I fixed it by going to Project Properties -> Debug and setting Hosting Model to "Out of Process".

That has nothing to do with Swagger endpoints.

Perhaps you unchecked **Enable OpenAPI support**

![image](https://user-images.githubusercontent.com/3605364/109740537-82bddf80-7b6f-11eb-8ea9-cc474890b5cf.png)

**Comment by rajalaxmijena** [comment]
> 
> 
> Most likely you don't have .NET 5 installed or unchecked **Enable OpenAPI support**
> 
> ![image](https://user-images.githubusercontent.com/3605364/109740537-82bddf80-7b6f-11eb-8ea9-cc474890b5cf.png)

this solution worked for me

**Comment by drock702** [comment]
I'm trying this tutorial on my MacBook, and I see the WeatherForecast page, but the swagger page is not loading.
The page never loads, it is just blank.
Do I need to install anything else?

**Comment by paulzolnierczyk** [comment]
> I'm trying this tutorial on my MacBook, and I see the WeatherForecast page, but the swagger page is not loading.
> The page never loads, it is just blank.
> I have .NET 5 installed and I checked Enable OpenAPI support

I'm in the same situation as @drock702

**Comment by drock702** [comment]
> > I'm trying this tutorial on my MacBook, and I see the WeatherForecast page, but the swagger page is not loading.
> > The page never loads, it is just blank.
> > I have .NET 5 installed and I checked Enable OpenAPI support
> 
> I'm in the same situation as @drock702

@paulzolnierczyk - I got it to work by installing Swagger/Swashbuckle package and "Rebuild All" my project.
https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-5.0&tabs=visual-studio-mac

**Comment by Rick-Anderson** [comment]
@wadepickett  can you test this on macOS?

**Comment by rsoaresgouveia** [comment]
Hello. Im currently using Visual Studio on Mac, and in tutorial page the swagger initial configuration for it to work is missing. So in "Test your project" section, the swagger configuration is missing, leaving <Your-Solution>/Startup.cs as follows:
.
.
.
` // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {

            services.AddControllers();

            //Swagger configuration
            services.AddSwaggerGen(c =>
            {
                c.SwaggerDoc("v1", new OpenApiInfo { Title = "TodoApi", Version = "v1" });
            });
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                app.UseSwagger();
                app.UseSwaggerUI(c => c.SwaggerEndpoint("/swagger/v1/swagger.json", "TodoApi v1"));

            }

            app.UseHttpsRedirection();

            app.UseRouting();

            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });
        }`
.
.
.

This bit of code necessary to configure swagger is shown in the same page in the section "Register the database context" (the lines commented).

I hope it helps.

**Comment by SwaraliJoshi** [comment]
I am still not able to run the test api provided in the "https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-5.0&tabs=visual-studio-code". localhost:5001(/swagger) shows just "This page isn’t workinglocalhost didn’t send any data.
ERR_EMPTY_RESPONSE"

Please help asap.

**Comment by paroqa02** [comment]
> Hello. Im currently using Visual Studio on Mac, and in tutorial page the swagger initial configuration for it to work is missing. So in "Test your project" section, the swagger configuration is missing, leaving /Startup.cs as follows:
> .
> .
> .
> `
> // This method gets called by the runtime. Use this method to add services to the container.
> public void ConfigureServices(IServiceCollection services)
> {
> 
> ```
>         services.AddControllers();
> 
>         //Swagger configuration
>         services.AddSwaggerGen(c =>
>         {
>             c.SwaggerDoc("v1", new OpenApiInfo { Title = "TodoApi", Version = "v1" });
>         });
>     }
> 
>     // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
>     public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
>     {
>         if (env.IsDevelopment())
>         {
>             app.UseDeveloperExceptionPage();
>             app.UseSwagger();
>             app.UseSwaggerUI(c => c.SwaggerEndpoint("/swagger/v1/swagger.json", "TodoApi v1"));
> 
>         }
> 
>         app.UseHttpsRedirection();
> 
>         app.UseRouting();
> 
>         app.UseAuthorization();
> 
>         app.UseEndpoints(endpoints =>
>         {
>             endpoints.MapControllers();
>         });
>     }`
> ```
> 
> .
> .
> .
> 
> This bit of code necessary to configure swagger is shown in the same page in the section "Register the database context" (the lines commented).
> 
> I hope it helps.

I try to paste the swagger config code to the startup.cs file , but getting error :(

**Comment by rsoaresgouveia** [comment]
I tried a new project to see what was happening. First go to your project root folder and run:

`dotnet add package Swashbuckle.AspNetCore -v 5.6.3`

This will add the Swashbuckle package into your project containing Swagger.
Than you can change your Startup.cs following:

```
  using Microsoft.AspNetCore.Builder;
  using Microsoft.AspNetCore.Hosting;
  using Microsoft.Extensions.Configuration;
  using Microsoft.Extensions.DependencyInjection;
  using Microsoft.Extensions.Hosting;
  using Microsoft.OpenApi.Models;

  namespace <your_namespace_here>
  {
      public class Startup
      {
          public Startup(IConfiguration configuration)
          {
              Configuration = configuration;
          }
          public IConfiguration Configuration { get; }
  
          public void ConfigureServices(IServiceCollection services)
          {
  
              services.AddControllers();
              services.AddSwaggerGen(c =>
              {
                  c.SwaggerDoc("v1", new OpenApiInfo { Title = "GpioService", Version = "v1" });
              });
          }
  
          // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
          public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
          {
              if (env.IsDevelopment())
              {
                  app.UseDeveloperExceptionPage();
                  app.UseSwagger();
                  app.UseSwaggerUI(c => c.SwaggerEndpoint("/swagger/v1/swagger.json", "GpioService v1"));
              }
  
              app.UseRouting();
  
              app.UseAuthorization();
  
              app.UseEndpoints(endpoints =>
              {
                  endpoints.MapControllers();
              });
          }
      }
  }
```

Just change your namespace to your project namespace.
For me it's working like a charm:
![Screen Shot 2021-09-01 at 18 51 57](https://user-images.githubusercontent.com/12357601/131756038-47edcef4-d9d0-4e71-8d44-58e8cfabf7cb.png)


I hope it helps.

**Comment by twakil** [comment]
Make sure you have the .NET 5.0 SDK installed and that .NET 5.0 is selected as the target framework in the project properties.  For those who are experiencing this problem on Windows, make sure you're using Chrome rather than IE to load the Swagger page.  In IE it just shows a blank page, but in Chrome it works.

**Comment by Rick-Anderson** [comment]
>  make sure you're using Chrome rather than IE to load the Swagger page. In IE it just shows a blank page, but in Chrome it works.

Edge works too. Thanks for the tip.

**Comment by paroqa02** [comment]
That's nice, thanks I will try all of your suggestions.

*Thanks*

*Paramita Roy*

*Senior Quality Assurance Analyst II (IT Analysis)*

*Mobile: +1 682-300-6222*


<https://www.linkedin.com/in/paramita-roy-297197104/>

**Comment by rohitsiddha** [comment]
Seems like a bug in macOS Visual Studio. While creating a web API project, the `Enable Open API support` checkbox works otherwise.
Uncheck it to add `/swagger` endpoint to your project. This is weird but worked.

<img width="919" alt="Screenshot 2021-11-23 at 4 29 42 AM" src="https://user-images.githubusercontent.com/1374513/143029152-4a0314ef-f6d5-4df8-80cf-f5de3b01b471.png">

**Comment by Rick-Anderson** [comment]
@rohitsiddha  why are you using .NET 5 and not .NET 6?

**Comment by kieron-cairns** [comment]
@rohitsiddha this happened to me too thank you

**Comment by mattsonnhalter** [comment]
@rohitsiddha Thank you for the the fix. What an odd bug. Deselecting Enable OpenAPI support actually enables it. I am using .Net 5 as well (the current recommendation for M1 Macs).

**Comment by bushra4468** [comment]
> Seems like a bug in macOS Visual Studio. While creating a web API project, the `Enable Open API support` checkbox works otherwise. Uncheck it to add `/swagger` endpoint to your project. This is weird but worked.
> 
> <img alt="Screenshot 2021-11-23 at 4 29 42 AM" width="919" src="https://user-images.githubusercontent.com/1374513/143029152-4a0314ef-f6d5-4df8-80cf-f5de3b01b471.png">

This worked for me! After hours of scrolling and downloading

**Comment by jhonatasmatos** [comment]
> Swashbuckle

it worked for me, thanks !!!!

**Comment by jhonatasmatos** [comment]
> Seems like a bug in macOS Visual Studio. While creating a web API project, the `Enable Open API support` checkbox works otherwise. Uncheck it to add `/swagger` endpoint to your project. This is weird but worked.
> 
> <img alt="Screenshot 2021-11-23 at 4 29 42 AM" width="919" src="https://user-images.githubusercontent.com/1374513/143029152-4a0314ef-f6d5-4df8-80cf-f5de3b01b471.png">

it worked for me, thanks !!!

**Comment by wadepickett** [comment]
Thanks very much to all of you who relayed your experience and identified the issue!

This appears to have been fixed and working as expected in the current version 17.6 (build 1575) of Visual Studio for Mac when targeting .NET 5.   The **Enable OpenAPI support** setting results in Swagger working properly.

I also verified it continues to work properly in the new Visual Studio 2022 for Mac Preview with .NET 5 and I checked the latest Visual Studio 2022 17.6.4 for windows and .NET 5.  Works as expected.

The prerequisites for the .NET 5 version of the tutorial point to the latest version of Visual Studio for Mac, which is what should be used.  I will add some text to clarify it is the latest version that is required in the prerequisites.

**Comment by wadepickett** [comment]
Fixed with #27363 
It was that PR completed after this issue was raised that we specified to use Visual Studio 2022 in the first step of the doc.

**Comment by wadepickett** [comment]
Fixed with #27363 .NET 7 MacOS: Tutorial: Create a web API
It was that PR completed after this issue was raised that we specified to use Visual Studio 2022 in the first step of the doc for all versions.

**Comment by aaditya-crypto** [comment]
> I have .NET 5 installed and was having the same problem. I fixed it by going to Project Properties -> Debug and setting Hosting Model to "Out of Process".

**Comment by fabiogoma** [comment]
This issue is still happening. My current SDK version is: 9.0.101

To reproduce the issue follow the VS Code steps from: [Tutorial: Create a web API with ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-9.0&viewFallbackFrom=aspnetcore-9.0%3Fns-enrollment-type%3Dcollection&ns-enrollment-id=25e1t683ymw6pg&tabs=visual-studio-code)

To make it shorter, run:
# Create a new project
dotnet new webapi --use-controllers -o TodoApi
cd TodoApi
dotnet add package Microsoft.EntityFrameworkCore.InMemory
code -r ../TodoApi

# Generate and trust self-signed certificates
dotnet dev-certs https --trust

# Start the app
dotnet run --launch-profile https

When you start the application and try to reach the swagger on your browser, you get a blank page.
Via curl the output is:
% curl -k -vvv https://localhost:7120/swagger/index.html
* Host localhost:7120 was resolved.
* IPv6: ::1
* IPv4: 127.0.0.1
*   Trying [::1]:7120...
* Connected to localhost (::1) port 7120
* ALPN: curl offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
* (304) (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384 / [blank] / UNDEF
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=localhost
*  start date: Nov 22 21:46:11 2024 GMT
*  expire date: Nov 22 21:46:11 2025 GMT
*  issuer: CN=localhost
*  SSL certificate verify ok.
* using HTTP/2
* [HTTP/2] [1] OPENED stream for https://localhost:7120/swagger/index.html
* [HTTP/2] [1] [:method: GET]
* [HTTP/2] [1] [:scheme: https]
* [HTTP/2] [1] [:authority: localhost:7120]
* [HTTP/2] [1] [:path: /swagger/index.html]
* [HTTP/2] [1] [user-agent: curl/8.7.1]
* [HTTP/2] [1] [accept: */*]
> GET /swagger/index.html HTTP/2
> Host: localhost:7120
> User-Agent: curl/8.7.1
> Accept: */*
>
* Request completely sent off
< HTTP/2 404
< date: Wed, 11 Dec 2024 08:30:14 GMT
< server: Kestrel
< content-length: 0
<
* Connection #0 to host localhost left intact

I hope you can reopen this one.

**Comment by fabiogoma** [comment]
> This issue is still happening. My current SDK version is: 9.0.101
> 
> To reproduce the issue follow the VS Code steps from: [Tutorial: Create a web API with ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-9.0&viewFallbackFrom=aspnetcore-9.0%3Fns-enrollment-type%3Dcollection&ns-enrollment-id=25e1t683ymw6pg&tabs=visual-studio-code)
> 
> ## To make it shorter, run:
> 
> ### Create a new project
> 
> dotnet new webapi --use-controllers -o TodoApi cd TodoApi dotnet add package Microsoft.EntityFrameworkCore.InMemory code -r ../TodoApi
> 
> ### Generate and trust self-signed certificates
> 
> dotnet dev-certs https --trust
> 
> ### Start the app
> 
> dotnet run --launch-profile https
> 
> When you start the application and try to reach the swagger on your browser, you get a blank page. Via curl the output is: % curl -k -vvv https://localhost:7120/swagger/index.html
> 
> * Host localhost:7120 was resolved.
> * IPv6: ::1
> * IPv4: 127.0.0.1
> * Trying [::1]:7120...
> * Connected to localhost (::1) port 7120
> * ALPN: curl offers h2,http/1.1
> * (304) (OUT), TLS handshake, Client hello (1):
> * (304) (IN), TLS handshake, Server hello (2):
> * TLSv1.2 (IN), TLS handshake, Certificate (11):
> * TLSv1.2 (IN), TLS handshake, Server key exchange (12):
> * TLSv1.2 (IN), TLS handshake, Server finished (14):
> * TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
> * TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
> * TLSv1.2 (OUT), TLS handshake, Finished (20):
> * TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
> * TLSv1.2 (IN), TLS handshake, Finished (20):
> * SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384 / [blank] / UNDEF
> * ALPN: server accepted h2
> * Server certificate:
> * subject: CN=localhost
> * start date: Nov 22 21:46:11 2024 GMT
> * expire date: Nov 22 21:46:11 2025 GMT
> * issuer: CN=localhost
> * SSL certificate verify ok.
> * using HTTP/2
> * [HTTP/2] [1] OPENED stream for https://localhost:7120/swagger/index.html
> * [HTTP/2] [1] [:method: GET]
> * [HTTP/2] [1] [:scheme: https]
> * [HTTP/2] [1] [:authority: localhost:7120]
> * [HTTP/2] [1] [:path: /swagger/index.html]
> * [HTTP/2] [1] [user-agent: curl/8.7.1]
> * [HTTP/2] [1] [accept: _/_]
> 
> > GET /swagger/index.html HTTP/2
> > Host: localhost:7120
> > User-Agent: curl/8.7.1
> > Accept: _/_
> 
> * Request completely sent off
>   < HTTP/2 404
>   < date: Wed, 11 Dec 2024 08:30:14 GMT
>   < server: Kestrel
>   < content-length: 0
>   <
> * Connection #0 to host localhost left intact
> 
> I hope you can reopen this one.

I've made a mistake while following the tutorial using the latest version (.NET 9), it is now known that .NET 9 removed swagger support from the templates, so it makes sense getting this 404 when calling it.

More info can be found at: https://learn.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-8.0&tabs=visual-studio

**Comment by AtheeshRathnaweera** [comment]
Swagger has been removed in .NET 9 and replaced with the built-in OpenAPI document generation. I came across this insightful article that explains the change in detail: [Built-in OpenAPI Document Generation with .NET 9 – No More SwaggerUI](https://abp.io/community/articles/builtin-openapi-document-generation-with-.net-9-no-more-swaggerui--au56cck5).

If you prefer not to downgrade to a version earlier than 9, you can still access the new document generation output at the following URL:

`https://localhost:<port>/openapi/v1.json`
